### ISSUE TITLE
monotonic: cannot add lists

### ISSUE THREAD

**Issue by bennn** [mvitousek/reticulated#18]
Two errors here. First, running this code:

```
def double_list(x:List(int)) -> List(int):
  return x + []

double_list([1])
```

Gives the error:
```
Traceback (most recent call last):
  File "/usr/local/bin/retic", line 5, in <module>
    retic.main()
  File "/home/ben/code/gradual/reticulated/retic/retic.py", line 149, in main
    reticulate(program, prog_args=args.args.split(), flag_sets=args)
  File "/home/ben/code/gradual/reticulated/retic/retic.py", line 98, in reticulate
    utils.handle_runtime_error(exit=True)
  File "/home/ben/code/gradual/reticulated/retic/retic.py", line 96, in reticulate
    _exec(code, __main__.__dict__)
  File "/home/ben/code/gradual/reticulated/retic/exec3/__init__.py", line 2, in _exec
    exec (obj, globs, locs)
  File "bug-list-add.py", line 4, in <module>
    double_list([1])
  File "/home/ben/code/gradual/reticulated/retic/rproxy.py", line 326, in __call__
    return self.__call__(*args, **kwds)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 380, in wrapper
    else: ret = val(*cargs, **ckwds)
  File "bug-list-add.py", line 2, in double_list
    return x + []
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 166, in retic_cast
    val.__monotonic_cast__(trg.type, msg, line)
  File "/home/ben/code/gradual/reticulated/retic/mono_datastructures.py", line 35, in __monotonic_cast__
    for i in range(self):
TypeError: 'MonoList' object cannot be interpreted as an integer
```

Replacing the empty list with `x`, the statement `return x + x` raises an internal error message:
```
Traceback (most recent call last):
  File "/usr/local/bin/retic", line 5, in <module>
    retic.main()
  File "/home/ben/code/gradual/reticulated/retic/retic.py", line 149, in main
    reticulate(program, prog_args=args.args.split(), flag_sets=args)
  File "/home/ben/code/gradual/reticulated/retic/retic.py", line 98, in reticulate
    utils.handle_runtime_error(exit=True)
  File "/home/ben/code/gradual/reticulated/retic/retic.py", line 96, in reticulate
    _exec(code, __main__.__dict__)
  File "/home/ben/code/gradual/reticulated/retic/exec3/__init__.py", line 2, in _exec
    exec (obj, globs, locs)
  File "bug-list-add.py", line 4, in <module>
    double_list([1])
  File "/home/ben/code/gradual/reticulated/retic/rproxy.py", line 326, in __call__
    return self.__call__(*args, **kwds)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 381, in wrapper
    return retic_mergecast(ret, src_ret, trg_ret, msg, line=line)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 400, in retic_mergecast
    return retic_cast(val, src, retic_merge(src, trg), msg, line)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 153, in retic_cast
    retic_inject(val, src, msg, line)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 133, in retic_inject
    retic_assert(isinstance(val, list), msg)
TypeError: retic_assert() missing 1 required positional argument: 'msg'
```

**Comment by mvitousek** [comment]
I believe Zeina's PR last week fixed this. Thanks Zeina!
