### ISSUE TITLE
monotonic: cannot put simple class in a list

### ISSUE THREAD

**Issue by bennn** [mvitousek/reticulated#20]
This program raises an error when run with monotonic casts. (Making a 1-element list works fine!)

```
class A:
  def a(self):
    return

[A(), A()]
```

Error message:
```
Traceback (most recent call last):
  File "/usr/local/bin/retic", line 5, in <module>
    retic.main()
  File "/home/ben/code/gradual/reticulated/retic/retic.py", line 155, in main
    reticulate(program, prog_args=args.args.split(), flag_sets=args)
  File "/home/ben/code/gradual/reticulated/retic/retic.py", line 107, in reticulate
    utils.handle_runtime_error(exit=True)
  File "/home/ben/code/gradual/reticulated/retic/retic.py", line 102, in reticulate
    _exec(code, __main__.__dict__)
  File "/home/ben/code/gradual/reticulated/retic/exec3/__init__.py", line 2, in _exec
    exec (obj, globs, locs)
  File "mlist.py", line 5, in <module>
    [A(), A()]
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 154, in retic_cast
    return retic_cast(val, src, trg, msg, line=line)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 176, in retic_cast
    return retic_monotonic_cast(val, src, trg, trg.members, msg, line)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 93, in retic_monotonic_cast
    new_mem_val = retic_cast(mem_val, srcty, trgty, msg, line=line)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 154, in retic_cast
    return retic_cast(val, src, trg, msg, line=line)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 159, in retic_cast
    return retic_make_function_wrapper(val, src, trg, msg, line)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 341, in retic_make_function_wrapper
    base_val, base_src, join = retic_check_threesome(val, src, trg, msg, line)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 331, in retic_check_threesome
    retic_assert(join.top_free(), val, msg)
  File "/home/ben/code/gradual/reticulated/retic/monotonic.py", line 23, in retic_assert
    raise exc(msg % val)
retic.monotonic.CastError: 
mlist.py:5:6: Constructed object value <bound method A.a of <__main__.A object at 0x7fbbf79dc390>> does not match type Object(A, {'a': Function([], Dyn)}),  expected for instances of Class(A, {'a': Function(['self:Dyn'], Dyn)}, ). Consider changing the type or setting it to Dyn. (code BAD_OBJECT_INJECTION)
```

**Comment by mvitousek** [comment]
Fixed. Thanks!
