### ISSUE TITLE
Cannot use enum with retic

### ISSUE THREAD

**Issue by migeed-z** [mvitousek/reticulated#27]
It seems that the enumeration class does not work with reticulated. Enum comes with python 3.4 and above.

The following code blows up: 

```
import enum
class MyClass(enum.Enum):
    A = 1
    B = 2
```

Error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/retic", line 9, in <module>
    load_entry_point('retic==0.1.0', 'console_scripts', 'retic')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/retic.py", line 155, in main
    reticulate(program, prog_args=args.args.split(), flag_sets=args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/retic.py", line 104, in reticulate
    utils.handle_runtime_error(exit=True)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/retic.py", line 102, in reticulate
    _exec(code, __main__.__dict__)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/exec3/__init__.py", line 2, in _exec
    exec (obj, globs, locs)
  File "misc.py", line 262, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/runtime.py", line 139, in check_type_class
    return val if val.__class__ is type else rse()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/runtime.py", line 88, in rse
    raise Exception(x)
Exception: None
Evolution $retic misc.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/retic", line 9, in <module>
    load_entry_point('retic==0.1.0', 'console_scripts', 'retic')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/retic.py", line 155, in main
    reticulate(program, prog_args=args.args.split(), flag_sets=args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/retic.py", line 104, in reticulate
    utils.handle_runtime_error(exit=True)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/retic.py", line 102, in reticulate
    _exec(code, __main__.__dict__)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/exec3/__init__.py", line 2, in _exec
    exec (obj, globs, locs)
  File "misc.py", line 262, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/runtime.py", line 139, in check_type_class
    return val if val.__class__ is type else rse()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/retic-0.1.0-py3.4.egg/retic/runtime.py", line 88, in rse
    raise Exception(x)
Exception: None
```

**Comment by migeed-z** [comment]
fixed by #23
